data_community:
  target: dev
  outputs: 
    dev:
      type: snowflake
      account: qh67427.ap-northeast-1.aws
      user: rashidmincan@gmail.com
      password: D%7$fbI12Bq7
      warehouse: ETL
      role: DBT_RW
      database: AIRBYTE_DATABASE
      schema: AIRBYTE_SCHEMA
      thread: 1


