name: Deployment
on:
  push:
    branches: [ dev ]

jobs:
  build-and-deploy-images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout dev
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push nginx
        uses: docker/build-push-action@v3
        with:
          context: ./twitter-streaming/nginx
          push: true
          tags: kingmoh/nginx:latest

      - name: Build and push tweet producer
        uses: docker/build-push-action@v3
        with:
          context: ./twitter-streaming/producer
          push: true
          tags: kingmoh/tweet_producer:latest

      - name: Build and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./twitter-streaming/backend
          push: true
          tags: kingmoh/dashboard-backend:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          context: ./twitter-streaming/frontend
          push: true
          tags: kingmoh/dashboard:latest

  push-files:
    needs: build-and-deploy-images
    runs-on: ubuntu-latest 
    steps:
      - name: checkout dev 
        uses: actions/checkout@v3
      - name: copy files via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: twitter-streaming/docker-compose.yml
          target: /home/ubuntu
      - name: restart services 
        uses: appleboy/ssh-action@master 
        env:
          CLICKHOUSE_BASE_URL: ${{ secrets.CLICKHOUSE_BASE_URL }}
          CLICKHOUSE_USER: ${{ secrets.CLICKHOUSE_USER }} 
          CLICKHOUSE_PASSWORD: ${{ secrets.CLICKHOUSE_PASSWORD }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull kingmoh/dashboard:latest
            docker pull kingmoh/dashboard-backend:latest
            docker pull kingmoh/nginx:latest
            docker network create -d bridge fifa
            docker run -d --name frontend -it -p 3000:3000 --network fifa  --restart always kingmoh/dashboard:latest
            if [[ $? -ne 0 ]]; then docker restart frontend; fi
            docker run -d --name backend -it -p 9876:9876 --network fifa --restart always -e CLICKHOUSE_BASE_URL="${CLICKHOUSE_BASE_URL}" -e CLICKHOUSE_USER=${CLICKHOUSE_USER} -e CLICKHOUSE_PASSWORD="${CLICKHOUSE_PASSWORD}" kingmoh/dashboard-backend:latest
            if [[ $? -ne 0 ]]; then docker restart backend; fi
            docker run -d --name nginx -it -p 3050:80 --network fifa --restart always kingmoh/nginx:latest
            if [[ $? -ne 0 ]]; then docker restart nginx; fi