name: Integration
on:
  push:
    branches: [ dev ]

env:
  host: ${{ secrets.CLICKHOUSE_BASE }}
  password: ${{ secrets.CLICKHOUSE_PASSWORD }}

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: checkout main 
        uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies 
        run: |
          cd twitter-streaming/backend
          pip install -r requirements.txt
      - name: Test endpoints
        run: |
          echo "PYTHONPATH=twitter-streaming/backend" >> $GITHUB_ENV
          cd twitter-streaming/backend
          pytest 
      - name: Run dbt models
        run: |
          cd twitter-streaming/transformations
          dbt run --target prod


    

    