name: CI
on:
  push:
    branches: [ dev ]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: checkout dev 
        uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies 
        run: |
          cd twitter-streaming/producer
          pip install -r requirements.txt 
      - name: Set PythonPath 
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
      - name: Run producer tests 
        run: pytest 

    

    