name: Integration
on:
  push:
    branches: [ dev ]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: checkout dev 
        uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies 
        run: |
          cd twitter-streaming/backend
          pip install -r requirements.txt
      - name: Set Python path 
        run: |
          echo "PYTHONPATH=twitter-streaming/backend" >> $GITHUB_ENV
      - name: Test with pytest
        run: |
          pytest


    

    