name: PushFiles
on:
  push:
    branches: [ dev ]

jobs:
  push-files:
    runs-on: ubuntu-latest 
    steps:
      - name: checkout dev 
        uses: actions/checkout@v3
      - name: copy files via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: twitter-streaming
          target: /home/ubuntu
      - name: restart services 
        uses: appleboy/ssh-action@master 
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/twitter-streaming
            bash docker-compose restart 