name: CI/CD Pipeline
on:
  push:
    branches: [ main ]

jobs:
  build-nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Build and push 
        uses: docker/build-push-action@v3
        with:
          context: ./twitter-streaming/nginx
          push: true
          tags: kingmoh/nginx:latest

      
  # continuous-integration:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up Python 3.7
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.7
  #     - name: Install dependencies 
  #       run: pip install -r requirements.txt
  #     - name: Set PythonPath
  #       run: echo "PYTHONPATH=data-orchestration/dags" >> $GITHUB_ENV
  #     - name: Testing Tweet Extraction
  #       run: pytest data-orchestration/dags/tests/test.py 

  # continuous-deployment:
  #   runs-on: ubuntu-latest
  #   needs: [continuous-integration]
  #   if: github.ref == 'refs/heads/rashid'
  #   steps:
  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: us-east-1
  #     - name: Create CodeDeploy Deployment
  #       id: deploy
  #       run: |
  #         aws deploy create-deployment \
  #           --application-name dec-project-2 \
  #           --deployment-group-name DeploymentGroupName\
  #           --deployment-config-name CodeDeployDefault.OneAtATime \
  #           --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
