name: Workflow
on:
  push:
    branches: [ dev ]

env:
  host: ${{ secrets.CLICKHOUSE_BASE }}
  password: ${{ secrets.CLICKHOUSE_PASSWORD }}

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: checkout main 
        uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies 
        run: |
          cd twitter-streaming/backend
          pip install -r requirements.txt
      - name: Test endpoints
        run: |
          echo "PYTHONPATH=twitter-streaming/backend" >> $GITHUB_ENV
          cd twitter-streaming/backend
          pytest 

  deployment:
    runs-on: ubuntu-latest
    needs: integration
    steps:
      - name: checkout main
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push nginx
        uses: docker/build-push-action@v3
        with:
          context: ./twitter-streaming/nginx
          push: true
          tags: kingmoh/nginx:latest

      - name: Build and push tweet producer
        uses: docker/build-push-action@v3
        with:
          context: ./twitter-streaming/producer
          push: true
          tags: kingmoh/tweet_producer:latest

      - name: Build and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./twitter-streaming/backend
          push: true
          tags: kingmoh/dashboard-backend:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          context: ./twitter-streaming/frontend
          push: true
          tags: kingmoh/dashboard:latest

      - name: Install dependencies 
        run: |
          cd twitter-streaming/transformations
          pip install -r requirements.txt

      - name: Run dbt models
        run: |
          cd twitter-streaming/transformations
          dbt run --target prod
          
  restart-services:
    needs: deployment
    runs-on: ubuntu-latest 
    steps:
      - name: checkout dev 
        uses: actions/checkout@v3
      - name: restart services 
        uses: appleboy/ssh-action@master 
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd $HOME/twitter-streaming
            . ./restart_services.sh


    

    